Update github-tmpl-update-apache-homepage.yml

diff --git a/.github/workflows/github-tmpl-update-apache-homepage.yml b/.github/workflows/github-tmpl-update-apache-homepage.yml
--- a/.github/workflows/github-tmpl-update-apache-homepage.yml
+++ b/.github/workflows/github-tmpl-update-apache-homepage.yml
@@ -39,48 +39,50 @@ jobs:
       NAME: ${{ steps.set-vars.outputs.NAME }}
       PAGE_TEXT: ${{ steps.set-vars.outputs.PAGE_TEXT }}
     steps:
-      - name: prepare variables for the next job
+      - name: Prepare variables for the next job
         id: set-vars
         run: |
           echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_OUTPUT
           echo "NAME=${{ inputs.name }}" >> $GITHUB_OUTPUT
           echo "PAGE_TEXT=${{ inputs.page_text }}" >> $GITHUB_OUTPUT
-  
-  
+
   validate_inputs:
     runs-on: ubuntu-latest
-    needs:  set_variables
+    needs: set_variables
     outputs: 
       NAME: ${{ steps.set-default-vars.outputs.NAME }}
       PAGE_TEXT: ${{ steps.set-default-vars.outputs.PAGE_TEXT }}
     steps:
       - name: Validate And Set Environment Variable
         run: |
-             if [[ -z "${{ steps.set-vars.outputs.ENVIRONMENT }}" ]]; then
-               echo " ERROR: Environment is not defined"
-               exit 1
-             fi
-             
+          if [[ -z "${{ needs.set_variables.outputs.ENVIRONMENT }}" ]]; then
+            echo " ERROR: Environment is not defined"
+            exit 1
+          fi
+
       - name: Validate Name Variable
         id: validate-or-set-default-name
         run: |
-             if [[ -z "${{ steps.set-vars.outputs.NAME }}" ]]; then
-                NAME="Default_Name_auto"
-             fi
- 
+          if [[ -z "${{ needs.set_variables.outputs.NAME }}" ]]; then
+            echo "NAME=Default_Name_auto" >> $GITHUB_ENV
+          else
+            echo "NAME=${{ needs.set_variables.outputs.NAME }}" >> $GITHUB_ENV
+          fi
+
       - name: Validate Page Text Variable
         id: validate-or-set-default-page-text
         run: |
-          if [[ -z "${{ steps.set-vars.outputs.PAGE_TEXT }}" ]]; then
-            $inputs.page_text="Default_Page_Text_auto"
+          if [[ -z "${{ needs.set_variables.outputs.PAGE_TEXT }}" ]]; then
+            echo "PAGE_TEXT=Default_Page_Text_auto" >> $GITHUB_ENV
+          else
+            echo "PAGE_TEXT=${{ needs.set_variables.outputs.PAGE_TEXT }}" >> $GITHUB_ENV
           fi
 
-       
-      - name: prepare variables for the next job
+      - name: Prepare variables for the next job
         id: set-default-vars
         run: |
-          echo "NAME=${{ steps.set-vars.outputs.NAME }}" >> $GITHUB_OUTPUT
-          echo "PAGE_TEXT=${{ steps.set-vars.outputs.PAGE_TEXT }}" >> $GITHUB_OUTPUT
+          echo "NAME=$NAME" >> $GITHUB_OUTPUT
+          echo "PAGE_TEXT=$PAGE_TEXT" >> $GITHUB_OUTPUT
 
 
 
